DROP TABLE IF EXISTS usuarios;
CREATE TABLE usuarios(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    age INTEGER CHECK(age >= 18),
    name TEXT UNIQUE NOT NULL,
    user TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,

    
);